---
# bring back stackd down
- hosts: loadbalancer
  gather_facts: false
  become: true
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: webserver
  gather_facts: false
  become: true
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

# restart mysql
- hosts: database
  become: true
  tasks:
    - service: name=mysql state=restarted
    - wait_for: host={{ ansible_eth1.ipv4.address }} port=3306 state=started

- hosts: webserver
  gather_facts: false
  become: true
  tasks:
    - service: name=apache2 state=started
    - wait_for: port=80

- hosts: loadbalancer
  gather_facts: false
  become: true
  tasks:
    - service: name=nginx state=started
    - wait_for: port=80
  